"""
api/v1/classify.py
------------------
FastAPI router for the company JD classification endpoint.

Endpoint
--------
  POST /api/v1/classify-company

Flow
----
  1. Receive { company_name, jd_text } from the Chrome Extension.
  2. Look up `company_name` in the MongoDB `classifications` collection.
  3. Cache hit  → return the stored document immediately (HTTP 200, cached=True).
  4. Cache miss →
       a. Call llm_service.classify_jd(jd_text).
       b. Upsert the result into MongoDB.
       c. Return the data (HTTP 200, cached=False).
  5. Any unhandled error → HTTP 500 with a descriptive message.
"""

import logging
from datetime import datetime

from fastapi import APIRouter, HTTPException, Request

from models import ClassifyRequest, ClassifyResponse
from services import llm_service

logger = logging.getLogger(__name__)

router = APIRouter()


@router.post(
    "/classify-company",
    response_model=ClassifyResponse,
    summary="Classify a company's JD using Gemini AI",
    description=(
        "Accepts a company name and its raw JD text. "
        "Returns industry tags and key skills, either from the MongoDB cache "
        "or freshly generated by Google Gemini 1.5 Flash."
    ),
)
async def classify_company(payload: ClassifyRequest, request: Request) -> ClassifyResponse:
    """
    Classify a company's JD and return structured tags.

    - **company_name**: A unique identifier for the company (used as cache key).
    - **jd_text**: Raw job description / company description text to analyse.
    """
    db = request.app.state.db
    collection = db["classifications"]

    company_name = payload.company_name.strip()
    logger.info("Classify request received for company: '%s'", company_name)

    # ── 1. Check the MongoDB cache ────────────────────────────────────────────
    try:
        cached_doc = await collection.find_one(
            {"company_name": company_name},
            {"_id": 0},  # exclude the internal MongoDB _id from the result
        )
    except Exception as exc:
        logger.error("MongoDB read error for '%s': %s", company_name, exc)
        raise HTTPException(
            status_code=500,
            detail=f"Database error while checking cache: {exc}",
        )

    if cached_doc:
        logger.info("Cache HIT for company '%s'. Returning stored result.", company_name)
        return ClassifyResponse(**cached_doc, cached=True)

    # ── 2. Cache miss — call Gemini ───────────────────────────────────────────
    logger.info("Cache MISS for company '%s'. Calling Gemini.", company_name)

    try:
        llm_result = llm_service.classify_jd(payload.jd_text)
    except ValueError as exc:
        # Malformed / empty LLM response — surface as a 500 with detail
        logger.error("LLM returned invalid data for '%s': %s", company_name, exc)
        raise HTTPException(
            status_code=500,
            detail=f"AI classification failed: {exc}",
        )
    except Exception as exc:
        # Network or API quota error
        logger.exception("Unexpected LLM error for '%s': %s", company_name, exc)
        raise HTTPException(
            status_code=500,
            detail=f"AI service error: {exc}",
        )

    # ── 3. Upsert result into MongoDB ─────────────────────────────────────────
    now = datetime.utcnow()
    document = {
        "company_name": company_name,
        "industry_tags": llm_result["industry_tags"],
        "key_skills": llm_result["key_skills"],
        "updated_at": now,
    }

    try:
        await collection.update_one(
            {"company_name": company_name},
            {"$set": document},
            upsert=True,
        )
        logger.info("Upserted classification for '%s' into MongoDB.", company_name)
    except Exception as exc:
        # Log and continue — we can still return the result even if caching fails
        logger.error("MongoDB write error for '%s': %s", company_name, exc)

    return ClassifyResponse(**document, cached=False)
